substitutions:
  device_name: justyna
  friendly_name: "Pokoj Justyny"

esphome:
  name: ${device_name}
  friendly_name: "${friendly_name}"

packages:
  device: !include .sonoff_minir4_extreme.yaml
  common: !include .common.yaml
  xiaomi1: !include
    file: .xiaomi-lywsd03mmc
    vars:
      xiaomi_friendly_name:  Justyna
      xiaomi_name: justyna
  xiaomi2: !include
    file: .xiaomi-lywsd03mmc
    vars:
      xiaomi_friendly_name:  Mati
      xiaomi_name: mati
