substitutions:
  device_name: justyna
  friendly_name: "Pokoj Justyny"

esphome:
  name: ${device_name}
  friendly_name: "${friendly_name}"

packages:
  device: !include .sonoff_minir4_extreme.yaml
  common: !include .common.yaml
