substitutions:
  device_name: kuchnia

esphome:
  name: kuchnia
  friendly_name: "Kuchnia"

packages:
  device: !include .sonoff_minir4_extreme.yaml
  common: !include .common.yaml

#######################################
# Device specific Config Begins Below #
#######################################

light:
  - id: !extend light_1
    icon: mdi:string-lights
