substitutions:
  device_name: parking-lamp

esphome:
  name: parking-lamp
  friendly_name: "Parking Lamp"

esp8266:
  board: esp8285

packages:
  device: !include .sonoff_minir2.yaml
  common: !include .common.yaml

#######################################
# Device specific Config Begins Below #
#######################################

light:
  - platform: binary
    id: light_1
    name: ${device_name}
    icon: mdi:spotlight-beam
    restore_mode: restore_default_off
    output: relay_1

binary_sensor:
  - id: !extend button_1
    filters:
      - invert:
      - delayed_off: 50ms
    on_press:
      - light.toggle:
          id: light_1

  - id: !remove switch_s1
