substitutions:
  device_name: sypialnia
  friendly_name: Sypialnia

esphome:
  name: ${device_name}
  friendly_name: "${friendly_name}"

packages:
  device: !include .sonoff_minir4_extreme.yaml
  common: !include .common.yaml
