substitutions:
  device_name: wmbus

esphome:
  name: wmbus1
  comment: "WMBUS meter reader - wodomierz"

esp8266:
  board: d1_mini  # WeMos D1 Mini, esp-12f, 4MB flash

packages:
  common: !include .common.yaml
  meter1a: !include
    file: .wmbus-sensor.yaml
    vars:
      meter_id: '0xB8DAF9'    # Wodomierz glowny
  meter1b: !include
    file: .wmbus-sensor.yaml
    vars:
      meter_id: '0x416E67BE'  # Wodomierz ogrod
  # meter2: !include
  #   file: .wmbus-sensor.yaml
  #   vars:
  #     meter_id: '0xB8D4A5'    # Darek?
  # meter3: !include
  #   file: .wmbus-sensor.yaml
  #   vars:
  #     meter_id: '0xB8E554'    # Marek
  # meter4: !include
  #   file: .wmbus-sensor.yaml
  #   vars:
  #     meter_id: '0xB908FC'
  # meter5: !include
  #   file: .wmbus-sensor.yaml
  #   vars:
  #     meter_id: '0xB90A62'    # Jacek
  # meter6: !include
  #   file: .wmbus-sensor.yaml
  #   vars:
  #     meter_id: '0x41514C04'  # Beata?
  # meter7: !include
  #   file: .wmbus-sensor.yaml
  #   vars:
  #     meter_id: '0x41514C11'  # Łukasz?
  # meter8: !include
  #   file: .wmbus-sensor.yaml
  #   vars:
  #     meter_id: '0x40A8B9C9'
  # meter9: !include
  #   file: .wmbus-sensor.yaml
  #   vars:
  #     meter_id: '0x40F55952'

# override pins
wmbus:
  led_pin:
    number: GPIO2
    inverted: true
  gdo0_pin: GPIO0
  gdo2_pin: GPIO16

time:
  - platform: sntp
    id: time_sntp

# override defaults from .common.yaml
api:
  reboot_timeout: 0s  # don't reboot when no clients are connected

# wifi:
#   networks:
#     - ssid: *
#       password: *

i2c:
  id: i2c_bus_1
  frequency: 100kHz
  scan: true
  # scl: GPIO5
  # sda: GPIO4

sensor:
  - platform: bme280_i2c
    id: bme280_chip
    address: 0x76     # or 0x77 if jumper is soldered
    temperature:
      id: bme280_temperature
      name: "Temperature BME"
      oversampling: 8x
    pressure:
      id: bme280_pressure
      name: "Pressure BME"
      oversampling: 8x
    humidity:
      id: bme280_humidity
      name: "Humidity BME"
      oversampling: 8x

  - platform: sht3xd
    id: sht31d_chip
    address: 0x44
    temperature:
      name: "Temperature SHT"
      id: sht31d_temperature
    humidity:
      name: "Humidity SHT"
      id: sht31d_humidity
    update_interval: 60s

  - platform: template
    name: "Temperature"
    id: temperature
    icon: "mdi:thermometer"
    device_class: temperature
    state_class: measurement
    unit_of_measurement: "°C"
    lambda: |-
      return id(bme280_temperature).state;
    update_interval: 60s
    filters:
      - calibrate_linear:
          method: least_squares
          datapoints:
            - 10.4 -> 3.2
            - 18.2 -> 10.0 #?
            - 23.9 -> 17.8
            - 28.5 -> 22.7
